### ISSUE TITLE
running the code

### ISSUE THREAD

**Issue by shijunil** [sildar/potara#1]
Hello,
Can you please tell me how should I run this code. I have installed all dependencies. The instructions are not very clear. Should I run the commands in python

Regards
Shiju

**Comment by sildar** [comment]
Hi shijunil.

The code described in the how to is python code. You need to import potara, and then copy-paste the code in the how to. The only line that may be unclear is

`s.setDocuments([document.Document('pathtofilenumber' + n)
       for i in range(1,11)])`

Maybe it is clearer for you written this way : 

`for x in listoffiles:
  s.addDocument(document.Document(x))`

with listoffiles being a list of strings (the paths of the documents you are trying to summarize, e.g. "./docs/doc1.txt").

Hope this helps, if you're unfamiliar with python, I encourage you to follow some tutorials.

Sildar

**Comment by sildar** [comment]
I'm closing the issue now, please contact me if you have further questions.

**Comment by shijunil** [comment]
can you please send me the link to the reference paper
