### ISSUE TITLE
 Attempted to load /work/conda_envs/20200407/miniconda3/lib/python3.7/site-packages/potara/data/english.pickle

### ISSUE THREAD

**Issue by nimahassanpour** [sildar/potara#11]
When I run my code I get the following error:

![Untitled](https://user-images.githubusercontent.com/35977719/78725587-87ddc480-78f5-11ea-8c91-6a24216da497.png)

I ran 
>>> import nltk
>>> nltk.download('work')

but got the following error.

[nltk_data] Error loading work: Package 'work' not found in index
False

Can you please help me to solve this issue?

**Comment by sildar** [comment]
Hi, and sorry for the delay!

You shouldn't have to do a nltk.download('work'). This method is used to download models and data from nltk, and "work" does not refer to any existing package from nltk.

You do have to download some data though: 

`nltk.download('stopwords');
nltk.download('punkt')`

Hope this helps, you can look at the travis.yml file sections "before_install" and "instal". It shows every step needed for potara to run (albeit in a suboptimal format).
