### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by shijunil** [sildar/potara#2]
Can you please send me the reference paper for this code.
Thanks

**Comment by shijunil** [comment]
Also I m trying to understand and use the sentence fusion part of your code. Can you please guide me how to modify the code to only give me the text with sentence fusion.

Thanks

**Comment by shijunil** [comment]
`summarizing
GLPSOL: GLPK LP/MIP Solver, v4.52
Parameter(s) specified in the command line:
 --cpxlp /tmp/2680-pulp.lp -o /tmp/2680-pulp.sol
Reading problem data from '/tmp/2680-pulp.lp'...
519 rows, 259 columns, 1054 non-zeros
258 integer variables, all of which are binary
787 lines were read
GLPK Integer Optimizer, v4.52
519 rows, 259 columns, 1054 non-zeros
258 integer variables, all of which are binary
Preprocessing...
226 hidden packing inequaliti(es) were detected
503 rows, 258 columns, 1038 non-zeros
258 integer variables, all of which are binary
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  3.500e+01  ratio =  3.500e+01
GM: min|aij| =  8.059e-01  max|aij| =  1.241e+00  ratio =  1.540e+00
EQ: min|aij| =  6.665e-01  max|aij| =  1.000e+00  ratio =  1.500e+00
2N: min|aij| =  5.000e-01  max|aij| =  1.250e+00  ratio =  2.500e+00
Constructing initial basis...
Size of triangular part is 503
Solving LP relaxation...
GLPK Simplex Optimizer, v4.52
503 rows, 258 columns, 1038 non-zeros
*     0: obj =   0.000000000e+00  infeas =  0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Integer optimization begins...
+     0: mip =     not found yet <=              +inf        (1; 0)
+     0: >>>>>   0.000000000e+00 <=   0.000000000e+00   0.0% (1; 0)
+     0: mip =   0.000000000e+00 <=     tree is empty   0.0% (0; 1)
INTEGER OPTIMAL SOLUTION FOUND
Time used:   0.0 secs
Memory used: 0.6 Mb (638316 bytes)
Writing MIP solution to `/tmp/2680-pulp.sol'...
Traceback (most recent call last):
  File "summ.py", line 8, in <module>
    print(s.summary())
TypeError: 'list' object is not callable`

**Comment by shijunil** [comment]
Can you help me with this error

**Comment by sildar** [comment]
Hi,

The two papers that I used for this are described in the readme.

And I can't really help you with your error since you don't give me much to work with.
I can only guess that you don't give it correct documents. If you want more help, show me the code where you add documents to the summarizer.
