### ISSUE TITLE
Loading documents

### ISSUE THREAD

**Issue by Ken4scholars** [sildar/potara#3]
When I create a list of documents from _Document_ class and pass it to the Summarizer it takes much time running into minutes. Furthermore, when I call summarize, it throws an error that says  that the documents in the summarizer are actually strings not instances of the Document class. What's more, for the same amount of documents I pass to it, len(summarizer.documnets) returns different answers.
This is my code

 ```
sum = Summerizer()
sum.setDocuments([Document('tests/testdata/mytest/article' + str(i))
       for i in range(1,3)])
# my articles are: article1, artilce2, artilce3
sum.summerize()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/kenneth/PycharmProjects/potara/potara/summarizer.py", line 405, in summarize
    self.clusterSentences()
  File "/home/kenneth/PycharmProjects/potara/potara/summarizer.py", line 274, in clusterSentences
    for sentence in doc.stemTokens]
AttributeError: 'str' object has no attribute 'stemTokens'
```

**Comment by Ken4scholars** [comment]
```
When I create a list of documents from _Document_ class and pass it to the Summarizer it takes much time running into minutes. Furthermore, when I call summarize, it throws an error that says  that the documents in the summarizer are actually strings not instances of the Document class. What's more, for the same amount of documents I pass to it, len(summarizer.documnets) returns different answers.
This is my code


 `
sum = Summerizer()
sum.setDocuments([Document('tests/testdata/mytest/article' + str(i))
       for i in range(1,3)])
# my articles are: article1, artilce2, artilce3
sum.summerize()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/kenneth/PycharmProjects/potara/potara/summarizer.py", line 405, in summarize
    self.clusterSentences()
  File "/home/kenneth/PycharmProjects/potara/potara/summarizer.py", line 274, in clusterSentences
    for sentence in doc.stemTokens]
AttributeError: 'str' object has no attribute 'stemTokens'
`

**Comment by sildar** [comment]
Hi,

This seems very strange.

Please be sure to put a correct minimal example. Here you refer to Summerizer() instead of Summarizer() and summerize() instead of summarize().
I'm sure your code is correct, but it's hard to guess where your error might be if you do not put the exact code.

Also, you should have logging messages, please add them so I can check that the init goes as intended.

**Comment by Ken4scholars** [comment]
The typo was only made here. I wrote everything fine there. Anyway I have decided to load the documents independently before passing it to the Document class and it works. It takes a whole lot of time though. It took almost 30 minutes to pre-process a text of about 20 pages. 

However, I always get summary = [ ], no matter which text I try to summarise. I have tried several times. I don't really understand the code very well yet but I found this piece of code in the __selectedSentences()_ method

` # solve the problem
        problem.solve(GLPK())

        summary = []
        # get the sentences back
        for j in range(numsentences):
            if sentences[j].varValue == 1:
                summary.append(fullsentences[j])

        return summary
`
Is it normal that the return values of the problem solver are not used at all in the summary? I was thinking maybe that's the reason I always get an empty summary.
I have installed glpk and it shows the result on console so I'm sure it does it work quite well.
By the way you did not include glpk as one of the dependencies or things to install. I understand it can't be installed via pip, but you have to make it known that it is needed so people won't run into problems.

P.S: I'm a final year student and I'm doing my project  research in the area of multi-document summarization. I read your paper and I got interested. I want to see how your works as it will help me in my research/project. Thanks for your expected cooperation)

**Comment by sildar** [comment]
I'll check that the setDocuments() method works with lists comprehension when I have time. As for GLPK dependency you're right, I should extend the readme to include the dependencies listed in both the requirements.txt file and the .travis.yml file.

Preprocessing is indeed long (but done well, you could have better performance with a naive tokenization), but I have no idea of what 20 pages mean in terms of length, so I'll take a wild guess and suppose that everything works in the preprocessing step.

Regarding your current problem : 

The piece of code you show is normal. It does use the results from GLPK (the .varValue is 1 if GLPK elected that sentence to be part of the summary, and 0 if not).
How many documents do you give to the summarizer ? If it is less than 5, then it is normal to have an empty result. The code was originally created for summarizing >10 documents (e.g. DUC corpora) and the default parameters are set this way. Here is the __init__() of the summarizer : 

```
    def __init__(self, minbigramcount=4,
                 similaritymeasure=cosine, minsimilarity=0.3,
                 wordmodelfile=None):
        # continues ...
```

minbigramcount=4 means that if a bigram does not appear in at least 4 documents, it will be disregarded. Gillick & Fabre used such a threshold for their experiments. This is to avoid as much as possible adding a lot of very short sentences with very poor information.

A piece of advice for your project research : try to use a standard dataset for evaluation. Automatic summarization is very hard to evaluate and if you don't use a standard dataset, it will be pretty hard to compare with other state of the art algorithms.

Please let me know if this minbigramcount parameter was the source of the error.

**Comment by Ken4scholars** [comment]
Thanks a lot, that did the trick:)

I actually have a lot of other things I want to inquire from you so can I get your contact on a social network or something?

**Comment by sildar** [comment]
Glad you could work it out.

I'll send you an email to your @mail.ru adress.
