### ISSUE TITLE
Not printing the summary.

### ISSUE THREAD

**Issue by JafferWilson** [sildar/potara#5]
I have tried using the summarizer with the following text in the file `data/1.txt`
Here is the text I am using for summarization:  
https://gist.github.com/JafferWilson/50f3cb96beb5e78a6d731abc8ba1bc82

I have used the following command for running the program:
```
>>> from summarizer import Summarizer
>>> import document
>>> s = Summarizer()
>>> s.setDocuments([document.Document('data/1.txt')])
>>> s.summarize()
GLPSOL: GLPK LP/MIP Solver, v4.57
Parameter(s) specified in the command line:
 --cpxlp /tmp/19846-pulp.lp -o /tmp/19846-pulp.sol
Reading problem data from '/tmp/19846-pulp.lp'...
11 rows, 7 columns, 20 non-zeros
6 integer variables, all of which are binary
25 lines were read
GLPK Integer Optimizer, v4.57
11 rows, 7 columns, 20 non-zeros
6 integer variables, all of which are binary
Preprocessing...
4 hidden packing inequaliti(es) were detected
8 rows, 6 columns, 16 non-zeros
6 integer variables, all of which are binary
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
Constructing initial basis...
Size of triangular part is 8
Solving LP relaxation...
GLPK Simplex Optimizer, v4.57
8 rows, 6 columns, 16 non-zeros
*     0: obj =  -0.000000000e+00 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Integer optimization begins...
+     0: mip =     not found yet <=              +inf        (1; 0)
+     0: >>>>>   0.000000000e+00 <=   0.000000000e+00   0.0% (1; 0)
+     0: mip =   0.000000000e+00 <=     tree is empty   0.0% (0; 1)
INTEGER OPTIMAL SOLUTION FOUND
Time used:   0.0 secs
Memory used: 0.0 Mb (51924 bytes)
Writing MIP solution to '/tmp/19846-pulp.sol'...
>>> print s.summary
[]
```
As you can see there is nothing in the output of summary. Please help me if you have any solution for this sort of problem. Anyone?

**Comment by sildar** [comment]
Hi! Tanks for tour interest in potara!

From your example you seem to try summarizing a single document. Potara is made for multidocument summarization and aims at creating a single summary for a set of documents discussing a similar topic.
Is this helping?

**Comment by sildar** [comment]
I'll close this issue since it seems your use case was a bit different from what potara offers. Please, reopen one if this didn't solve your problem.

**Comment by JafferWilson** [comment]
So that means potara will work only on the multiple documents. I understood. Thank you for your time and help. :)
