### ISSUE TITLE
ModuleNotFoundError UserDict

### ISSUE THREAD

**Issue by Mabelle793** [sildar/potara#6]
Hi,
I tried to use this package but when I run the sample code I get this error:

`Traceback (most recent call last):
  File "C:\Users\xxx\scripts\multi_summarizer.py", line 4, in <module>
    from summarizer import Summarizer
  File "C:\Users\xxx\scripts\summarizer.py", line 22, in <module>
    import gensim
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\gensim\__init__.py", line 7, in <module>
    from gensim import utils, matutils, interfaces, corpora, models, similarities
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\gensim\corpora\__init__.py", line 12, in <module>
    from .dictionary import Dictionary
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\gensim\corpora\dictionary.py", line 22, in <module>
    import UserDict
ModuleNotFoundError: No module named 'UserDict'`

How can I solve this?

Python version used:
Python 3.7.0b4

**Comment by sildar** [comment]
Hi @Mabelle793 and thx for your interest in potara!

The issue comes from the version of gensim you have installed. This repository uses an older version (v0.9.1). You can find versions for every module used by potara in the requirements.txt file.

I'm afraid potara won't be compatible with Python 3 however (although I didn't test it). I'm considering spending some time improving it in the next few months, I'll definitely consider switching to Python 3.

If you don't need to use word2vec ("semantic" representation of words), you should be able to use potara by removing the gensim imports and word2vec related stuff in the summarizer.py file. I can work you through this process if you want me to.

**Comment by Mabelle793** [comment]
Hi @sildar . Thanks for your reply. 
I think UserDict was removed in Python 3. So if the removal of gensim and word2vec would fix this issue it would be very nice if you could guide me through the edits that need to be made.

**Comment by JafferWilson** [comment]
I guess try using this:
```
>>> try:
...     from UserDict import UserDict
...     from UserDict import DictMixin
... except ImportError:
...     from collections import UserDict
...     from collections import MutableMapping as DictMixin
```
Reference: http://python3porting.com/problems.html#replacing-userdict

**Comment by sildar** [comment]
It'd be best to just remove the gensim part as UserDict is only used in gensim.

So, remove those lines from summarizer:

``10: from gensim.models import word2vec
  179:  self.wordmodel = word2vec.Word2Vec.load(wordmodelfile)``

and I think that's it. I'll try quickly to load a py3 environment on my computer to test it.

**Comment by Mabelle793** [comment]
Hi @JafferWilson . I have already tried this, but it gave me the error

```
    from collections import MutableMapping as DictMixin
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

And so I tried 
`try:
    from UserDict import UserDict
    from UserDict import DictMixin
except ImportError:
    from collections.abc import UserDict
    from collections.abc import MutableMapping as DictMixin
`

which gives me the error
```

    from collections.abc import UserDict
ImportError: cannot import name 'UserDict' from 'collections.abc'
```

**Comment by sildar** [comment]
I won't be able to fully check this before a few hours.

It seems I have an issue with the most recent version of nltk, but it seems to be related to my Windows configuration. I'll try and dive into it later. With only the removal of the two lines I mentionned, it should work on a Linux configuration. Although remaking this whole process makes me realize some missing elements for a quick test (e.g. adding fake documents that match the Readme example).

**Comment by Mabelle793** [comment]
@sildar I removed those two lines but when I excute the python script I get the same error as before (in "import gensim"). I removed the compiled files (folder __pycache__) before.
Am I missing somethin? Do I need to update anything? Sorry for this question, but I haven´t edited a package manually before.

**Comment by Mabelle793** [comment]
I had saved the file. But it was my fault because I was at the wrong path. 
However, I get another error now: 


```
Warning (from warnings module):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\__init__.py", line 4
    from collections import Sequence
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Warning (from warnings module):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py", line 6
    from collections import Mapping
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Warning (from warnings module):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_split.py", line 18
    from collections import Iterable
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
Traceback (most recent call last):
  File "C:\Users\xxx\Dropbox\2017 spartaco Projekt Share\Python Skripte\multi_summarizer.py", line 6, in <module>
    import document
ModuleNotFoundError: No module named 'document'
```

**Comment by sildar** [comment]
This seems to also be a problem with your files.

Do you have summarizer.py/document.py/takahe.py/... files in the same directory as your multi_summarizer.py ? (in Python Skripte)

**Comment by Mabelle793** [comment]
No, they are in different directories.. All files of potara are in a folder which is in the Lib folder for Python37.

**Comment by sildar** [comment]
You can either put them in the same directory (the "import document" looks for files named document.py in the directory if no installed package exists) or fix the imports. If your system is correctly configurated, a "from potara import document" should work.

**Comment by Mabelle793** [comment]
Ok... I put all files in one folder. Now the module "document" is found but I had some nltk issues which I almost fixed by downloading required packages with the nltk downloader. But still, there is something weird which I cannot solve.
This is the error:

`LookupError: 
**********************************************************************
  Resource [93mC:[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('C:')
  [0m
  Searched in:
    - ''
**********************************************************************`

So I tried nltk.download('C:') but received the error

`[nltk_data] Error loading C:: Package 'C:' not found in index`

**Comment by sildar** [comment]
Regarding nltk, you should download the 'stopwords' package:

`nltk.download('stopwords')`

You can follow the .travis.yml file to see what should be installed.

**Comment by Mabelle793** [comment]
I already did.. When I try again I get

`[nltk_data]   Package stopwords is already up-to-date!`

But still I receive the above error.

**Comment by sildar** [comment]
I have no idea why you would have:

` >>> nltk.download('C:')`

Can you give the full stacktrace ?

**Comment by sildar** [comment]
OK this comes from this line:

`sentTokenizer = nltk.data.load('file:' + _currentdir +'/data/english.pickle')`

This looks for the english.pickle file which is supposed to be in the data/ directory next to the document.py script. Check that you do have the data directory. You can replace the "file: ..." with a custom filepath if you prefer.

Another solution is to download the english.pickle file directly from ntlk and replacing the line according to what you can see in [this SO question](https://stackoverflow.com/questions/4867197/failed-loading-english-pickle-with-nltk-data-load).

**Comment by sildar** [comment]
Hi!

I tested on Python 3 last night without too many issues. I'll try to make modifications and a release a Python 3 compatible version in the next few weeks. I also updated the Python 2.7 version on the repo, some libraries were too much out of date (glpk install, and nltk mainly). This had impact on some other parts of the code.

You can either keep debugging or wait a few weeks!

**Comment by sildar** [comment]
I'm closing this one for now. The Py3 update should hopefully come in the next few weeks. If you have more issues with installation, please reopen an issue.
